### ISSUE TITLE
请问下目录下的site-packages是什么意思啊

### ISSUE THREAD

**Issue by iloveyo123u1** [BeginMan/newBlog#4]
site-packages目录
我知道这个是python包
不过楼主放在这里是什么意思啊
是不是python会优先加载这里面的包啊

我是个新手 谢谢楼主指点

**Comment by BeginMan** [comment]
我把所需的包都放在这里了，用的时候直接copy到你本地python site-packages目录下就行了，这样就不必一个个的安装了。
主要有一些没法pip install 的包，可以直接copy进行硬性安装。

**Comment by zdiank** [comment]
还不是太明白，我在本地出错，’‘’‘’‘’‘’‘’用的时候直接copy到你本地python site-packages目录下就行了‘’‘’‘啥意思啊，能在明确点吗？？我是小白请指点，，实在本地建个这个目录吗
